### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by k79e** [SamLex/mcudpt#1]
./mcudpt.go: line 1: /appex: is a directory
./mcudpt.go: line 2: syntax error near unexpected token `c'
./mcudpt.go: line 2:`Copyright (c) 2014, SamLex (Euan James Hunter)'

**Comment by SamLex** [comment]
Could you please give some more information about this error? Was it when building the code or running the program? Did you run 'go get github.com/SamLex/mcudpt' to get the code and program?

**Comment by SamLex** [comment]
Could you please give some more information about this error? Was it when building the code or running the program? Did you run 'go get github.com/SamLex/mcudpt' to get the code and program?

**Comment by SamLex** [comment]
Could you please give some more information about this error? Was it when building the code or running the program? Did you run 'go get github.com/SamLex/mcudpt' to get the code and program?

**Comment by k79e** [comment]
Oops... I forget to run 'go get github.com/SamLex/mcudpt'
Now it works fine
